name: geminio_imagenet

defaults:
  - data: GeminioImageNet
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_
model: ResNet34

# Server and user:
num_queries: 1

user:
  num_data_points: 128
