name: geminio_cifar20

defaults:
  - data: GeminioFER
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_
model: ResNet18

# Server and user:
num_queries: 1

user:
  num_data_points: 9
